### PR TITLE
Add support for Carthage.

### PR DESCRIPTION
**Pull request by mattprowse**
Adds an Xcode project with a Framework target so that MASPreferences can be built by Carthage.

I also had to bump the Deployment Target from 10.5 to 10.6 to get rid of a warning when building with Xcode 7 on OS X 10.11.

I needed this for my own use so I just threw it together quickly, but I'm happy to put some more work into it if required.

### CODE REVIEW

**Comment by shpakovski** [comment]
`MASPreferences` is used in TextMate which needs 10.5 support, so I have not merged the Pull Request, sorry. But I will make a reference to your branch, thanks a lot!

**Comment by sorbits** [comment]
I appreciate the consideration :) but TextMate is (now) using 10.7 as 
deployment target, so this PR shouldn’t cause any problems for me.

**Comment by shpakovski** [comment]
Glad to hear that Allan, thank you for the heads up! @mattprowse Could you please resolve the conflict I introduced by another Merge? Sorry for inconvenience.

**Comment by mattprowse** [comment]
Not a worry at all. Should be good to go now!

**Comment by shpakovski** [comment]
Thanks!

**Comment by konstantinpavlikhin** [comment]
Guys, this change broke the installation via Cocoapods. The MASPreferencesWindow.xib is no longer treated as a pod resource.

**Comment by shpakovski** [comment]
@konstantinpavlikhin Yay, thank you very much for the heads up! Could you make a Pull Request please?

**Pull request merged**
