### PR TITLE
Adds nullability annotations

### PR DESCRIPTION
**Pull request by mz2**
- Adds nullability annotations to `MASPreferencesViewController.h` and `MASPreferencesWindowController.h`
- Toggles on some Xcode 8 suggested compiler warnings in the framework target.

### CODE REVIEW

**Comment by shpakovski** [comment]
Thank you for the Pull Request Matias.

Sorry, but it has too many commits from your local project plus unnecessary changes in `.gitignore`, `project.pbxproj` and `MASPreferences.xcscheme`. Also, I would prefer `NS_ASSUME_NONNULL_BEGIN`/`NS_ASSUME_NONNULL_END` with `_Nullable`.

Could you please rewrite all changes as a single commit and maybe “force-push” it? Thanks in advance and sorry again 😊

**Comment by mz2** [comment]
@shpakovski: I'm happy to squash the commits to a single one (the version history is messy, though the actual changes not really), however would need a bit more guidance:

- the changes in .gitignore are not really unnecessary (unless you mean specifically in the context of adding nullability annotations) – if you use carthage with `--use-submodules` on, you can end up with `Carthage/Build` under your framework dependency.

- the additional compiler warnings are arguably unnecessary again in the context of adding nullability – what I was really doing is modernising for current conventions. It tends to be a good idea to build a target with as restrictive compiler error / warning settings as possible, wouldn't you say?

- Re: `NS_ASSUME_NONNULL_BEGIN` / `NS_ASSUME_NONNULL_END` do you mean specifically around the constant? I feel doing that more globally around that header will just result in worse readability as there is quite the mix of nullability and non-nullability to go there.

**Comment by mz2** [comment]
Basically, if you could annotate the changes you'd like to see under https://github.com/shpakovski/MASPreferences/pull/48/files that would help me make sure I know what you'd like changed / dropped from the PR.

**Comment by sorbits** [comment]
> unless you mean specifically in the context of adding nullability annotations

Correct, this PR should contain a single commit that only adds the nullability annotations.

No merge commits, you should always rebase against `origin/master` prior to submitting a PR.

No commits “fixing” prior commits in the same PR, you should present us with the minimal number of commits required to bring the code base into the new desired state (i.e. the one with the nullability annotations).

No commits unrelated to the nullability annotations, since this PR is about adding these annotations, you can submit another PR for other changes.

Though you are welcome to submit one PR for multiple changes, but then the commit history should be so that we can cherry-pick the things we want, incase we do not agree with all your changes.

For example if we just want to take the nullability annotations we actually need to cherry-pick two commits, possibly four, since there are also two merge commits that may also have made changes here.

**Comment by shpakovski** [comment]
@mz2 I will add `nullability` annotations, thank you very much for the heads up!

**Comment by shpakovski** [comment]
@mz2 Could you please verify the changes? Thanks in advance!

**Comment by mz2** [comment]
Looks good! I tend to do nullability annotations always for local readability, but that certainly does read out better. I posted the .gitignore tweak as a separate PR.

**Pull request closed without merging**
