### PR TITLE
Removed deployment_target from Podspec

### PR DESCRIPTION
**Pull request by josh64x2**
This fixes issues such as:

- https://github.com/CocoaPods/CocoaPods/issues/4952
- https://github.com/ViennaRSS/vienna-rss/issues/576

### CODE REVIEW

**Comment by shpakovski** [comment]
Thank you for the heads up! Why not 10.6?

**Comment by josh64x2** [comment]
I think it is OK to leave it blank. https://guides.cocoapods.org/syntax/podspec.html#deployment_target says this if it is blank then it will assume it works on OS X < 10.8 as well.

I looked at a couple of other cocoapods that we use and they all left it blank.

Thank you for your work with MASPreferences!

**Comment by shpakovski** [comment]
Thanks for the PR!

**Comment by mackuba** [comment]
@josh64x2 thanks!

@shpakovski can you push the updated podspec to CocoaPods?

**Comment by shpakovski** [comment]
@mackuba Yes, could you please advise how do I do this?

> 1. Bump tag `1.1.2` to `1.1.3` in the new `master` commit
2. Then add the new tag `1.1.3` to that commit and push it to `origin`

Correct?

**Comment by josh64x2** [comment]
@shpakovski I would change the version number in the Podspec to 1.1.3 as well, and then follow the instructions from here: https://guides.cocoapods.org/making/specs-and-specs-repo.html

##How do I update an existing Pod?

1.     Create your Podspec as described above.
2.     Run pod spec lint to check for errors.
3.     Submit your Podspec to Trunk with pod trunk push NAME.podspec

I've never done it before so this is just a guess :smile:

**Comment by shpakovski** [comment]
Alright, I updated repository for the new version, but `pod trunk push MASPreferences.podspec` gives an error `[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session`. I don't remember how I did this last time, sorry 😅

**Comment by josh64x2** [comment]
Haha what a helpful error. Try this : https://guides.cocoapods.org/making/getting-setup-with-trunk.html 😊

**Comment by shpakovski** [comment]
It worked! Thank you so much Josh. Could you please verify the new version?

**Comment by josh64x2** [comment]
It works here :smile:  thanks for the quick response!

**Pull request merged**
